// <auto-generated />
using System;
using JobBoard.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobBoard.Infrastructure.Migrations
{
    [DbContext(typeof(JobBoardContext))]
    partial class JobBoardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobBoard.Domain.Entities.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Applicants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "marko.markovic@example.com",
                            FirstName = "Marko",
                            LastName = "Markovic",
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 2,
                            Email = "jovana.jovanovic@example.com",
                            FirstName = "Jovana",
                            LastName = "Jovanovic",
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 3,
                            Email = "petar.petrovic@example.com",
                            FirstName = "Petar",
                            LastName = "Petrovic",
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "ana.anic@example.com",
                            FirstName = "Ana",
                            LastName = "Anic",
                            YearsOfExperience = 3
                        });
                });

            modelBuilder.Entity("JobBoard.Domain.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobPostingId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("JobPostingId", "ApplicantId")
                        .IsUnique();

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicantId = 1,
                            AppliedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CoverLetter = "Zainteresovan sam za poziciju Frontend Developer-a.",
                            JobPostingId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            ApplicantId = 2,
                            AppliedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CoverLetter = "Imam petogodisnje iskustvo u backend razvoju.",
                            JobPostingId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            ApplicantId = 3,
                            AppliedAt = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobPostingId = 3,
                            Status = 2
                        });
                });

            modelBuilder.Entity("JobBoard.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Belgrade",
                            Industry = "IT",
                            Name = "TechCorp"
                        },
                        new
                        {
                            Id = 2,
                            City = "Novi Sad",
                            Industry = "Finance",
                            Name = "FinancePro"
                        },
                        new
                        {
                            Id = 3,
                            City = "Nis",
                            Industry = "Construction",
                            Name = "BuildIt"
                        });
                });

            modelBuilder.Entity("JobBoard.Domain.Entities.JobPosting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionsFilled")
                        .HasColumnType("int");

                    b.Property<int>("PositionsTotal")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("JobPostings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Deadline = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Razvoj i odrzavanje backend servisa.",
                            PositionsFilled = 1,
                            PositionsTotal = 3,
                            Status = 0,
                            Title = "Backend Developer"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Deadline = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Razvoj korisnickog interfejsa.",
                            PositionsFilled = 0,
                            PositionsTotal = 2,
                            Status = 0,
                            Title = "Frontend Developer"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            Deadline = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vodjenje finansijske evidencije.",
                            PositionsFilled = 0,
                            PositionsTotal = 1,
                            Status = 1,
                            Title = "Accountant"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 3,
                            Deadline = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nadzor gradjevinskih radova.",
                            PositionsFilled = 0,
                            PositionsTotal = 2,
                            Status = 0,
                            Title = "Site Engineer"
                        });
                });

            modelBuilder.Entity("JobBoard.Domain.Entities.Application", b =>
                {
                    b.HasOne("JobBoard.Domain.Entities.Applicant", "Applicant")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobBoard.Domain.Entities.JobPosting", "JobPosting")
                        .WithMany("Applications")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("JobBoard.Domain.Entities.JobPosting", b =>
                {
                    b.HasOne("JobBoard.Domain.Entities.Company", "Company")
                        .WithMany("JobPostings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("JobBoard.Domain.Entities.Applicant", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("JobBoard.Domain.Entities.Company", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("JobBoard.Domain.Entities.JobPosting", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
